name: LateX to PDF

on:
  push:
    branches: 
      - main
      - develop
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX to PDF
        run: docker run --rm -i -v $(pwd):/data mingc/latex pdflatex main.tex
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: main.pdf
